package com.ozkanmut.ilactakip

import android.content.Context
import android.content.ContextWrapper
import androidx.test.core.app.ApplicationProvider
import com.google.crypto.tink.Aead
import com.google.crypto.tink.KeysetHandle
import com.google.crypto.tink.RegistryConfiguration
import com.google.crypto.tink.aead.AeadConfig
import com.google.crypto.tink.aead.PredefinedAeadParameters
import com.google.crypto.tink.hybrid.HybridConfig
import com.google.crypto.tink.signature.SignatureConfig
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertSame
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.IOException
import java.security.GeneralSecurityException
import java.util.Base64
import java.util.UUID

/**
 * RED contract for Task 12's encrypted relay transport.
 *
 * Intended minimal API (all storage is device-local):
 * - RelayApi(httpsBaseUrl, installCredential, RelayApiHttp) fails closed for non-HTTPS bases,
 *   validates/redacts the authenticated HTTP boundary, and exposes routes(), enqueue(envelope),
 *   inbox(), and acknowledge(terminalAcks).
 * - RelayOutbox(context, localInstallId, RelayCrypto, RelayPeerStore, RelayApi) materializes one
 *   durable RelayOutboundEnvelope per trusted route, then flushes the durable records without
 *   regenerating message IDs or ciphertext after a transport failure.
 * - RelayInbox(context, localInstallId, RelayCrypto, RelayPeerStore, RelayApi, RelayInboxFaults)
 *   processes a non-destructive inbox to durable terminal outcomes before batching ACKs.
 * - RelaySyncTransport(outbox, inbox) is injectable but SyncTransportRuntime remains ntfy until
 *   Task 16's atomic cutover. RelayApiHttp is the only HTTP double; RelayInboxFaults is the only
 *   fault-injection seam.
 *
 * Fixture identities are generated by the real RelayIdentityStore and envelopes by real
 * RelayCrypto. Assertions intentionally inspect no key material, credential, or plaintext payload.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [35])
class RelayTransportTest {
    private lateinit var sender: Device
    private lateinit var recipient: Device
    private lateinit var http: ScriptedRelayHttp
    private lateinit var senderApi: RelayApi
    private lateinit var recipientApi: RelayApi

    @Before
    fun setUp() {
        AeadConfig.register()
        HybridConfig.register()
        SignatureConfig.register()
        sender = device(SENDER_INSTALL)
        recipient = device(RECIPIENT_INSTALL)
        http = ScriptedRelayHttp()
        senderApi = RelayApi(RELAY_URL, TEST_INSTALL_CREDENTIAL, http)
        recipientApi = RelayApi(RELAY_URL, TEST_INSTALL_CREDENTIAL, http)
        check(recipient.peers.pin(sender.installId, sender.identity))
        allowSenderInRecipientGuard()
    }

    // Mutation caught: create ciphertext only in memory, regenerate it/message ID after failure,
    // or mark its source event synced before the relay has accepted every materialized recipient.
    @Test
    fun offlineSenderPersistsOneRecipientEnvelopeAndRetriesTheSameRecordAfterReconstruction() {
        val event = localEvent(EVENT_ID)
        EventStore.append(sender.context, event)
        assertTrue(sender.peers.pin(recipient.installId, recipient.identity))
        http.routes = listOf(route(ROUTE_ID, recipient))
        http.enqueueFailure = IOException("TEST-ONLY offline")
        val firstOutbox = sender.outbox(senderApi)

        assertFalse(firstOutbox.flush())
        val persisted = firstOutbox.recordsFor(EVENT_ID).single()
        assertEquals("pending", EventStore.load(sender.context).single { it.eventId == EVENT_ID }.syncState)

        http.enqueueFailure = null
        val reconstructed = sender.outbox(senderApi)
        assertTrue(reconstructed.flush())

        val accepted = http.acceptedEnvelopes.single()
        assertEquals(persisted.outerContext.messageId, accepted.outerContext.messageId)
        assertArrayEquals(persisted.ciphertext, accepted.ciphertext)
        assertEquals("synced", EventStore.load(sender.context).single { it.eventId == EVENT_ID }.syncState)
        assertTrue(reconstructed.recordsFor(EVENT_ID).isEmpty())
    }

    // Mutation caught: encrypt once for multiple routes, trust a server key, or omit route/key data
    // from the sealed outer context.
    @Test
    fun outboxEncryptsIndependentlyPerPinnedRecipientAndRejectsServerKeySubstitution() {
        val otherRecipient = device("TEST-ONLY-recipient-b")
        val event = localEvent(EVENT_ID).copy(targetTopic = "")
        EventStore.append(sender.context, event)
        sender.peers.pin(recipient.installId, recipient.identity)
        sender.peers.pin(otherRecipient.installId, otherRecipient.identity)
        http.routes = listOf(route(ROUTE_ID, recipient), route(ROUTE_ID_B, otherRecipient))

        val outbox = sender.outbox(senderApi)
        assertEquals(2, outbox.materializePending())
        val records = outbox.recordsFor(EVENT_ID)

        assertEquals(setOf(ROUTE_ID, ROUTE_ID_B), records.map { it.outerContext.routeId }.toSet())
        assertEquals(setOf(recipient.installId, otherRecipient.installId),
            records.map { it.outerContext.recipientInstallId }.toSet())
        assertFalse(records[0].ciphertext.contentEquals(records[1].ciphertext))

        EventStore.append(sender.context, localEvent(EVENT_SUBSTITUTION_ID))
        http.routes = listOf(route(ROUTE_ID, recipient).copy(recipientIdentity = otherRecipient.identity))
        assertEquals(0, outbox.materializePending())
        assertTrue(outbox.recordsFor(EVENT_SUBSTITUTION_ID).isEmpty())
    }

    // Mutation caught: fan out a nonblank recipient-bound event to every active route instead of
    // materializing exactly one envelope for its intended recipient.
    @Test
    fun targetedOutboxEventMaterializesOnlyItsExactRecipientRoute() {
        val otherRecipient = device("TEST-ONLY-targeted-recipient-b")
        EventStore.append(sender.context, localEvent(EVENT_ID))
        assertTrue(sender.peers.pin(recipient.installId, recipient.identity))
        assertTrue(sender.peers.pin(otherRecipient.installId, otherRecipient.identity))
        http.routes = listOf(route(ROUTE_ID, recipient), route(ROUTE_ID_B, otherRecipient))

        assertEquals(1, sender.outbox(senderApi).materializePending())

        assertEquals(listOf(recipient.installId), sender.outbox(senderApi).recordsFor(EVENT_ID)
            .map { it.outerContext.recipientInstallId })
    }

    // Mutation caught: rematerialize the already accepted recipient after another recipient fails.
    @Test
    fun partialRecipientAcceptanceSurvivesReconstructionWithoutResendingAcceptedEnvelope() {
        val other = device("TEST-ONLY-partial-b")
        EventStore.append(sender.context, localEvent(EVENT_ID).copy(targetTopic = ""))
        sender.peers.pin(recipient.installId, recipient.identity); sender.peers.pin(other.installId, other.identity)
        http.routes = listOf(route(ROUTE_ID, recipient), route(ROUTE_ID_B, other))
        http.failingRecipients = setOf(other.installId)
        assertFalse(sender.outbox(senderApi).flush())
        val firstAccepted = http.acceptedEnvelopes.single().outerContext.messageId
        http.failingRecipients = emptySet()
        assertTrue(sender.outbox(senderApi).flush())
        assertEquals(2, http.acceptedEnvelopes.size)
        assertEquals(firstAccepted, http.acceptedEnvelopes[0].outerContext.messageId)
        assertEquals("synced", EventStore.load(sender.context).single { it.eventId == EVENT_ID }.syncState)
    }

    // Mutation caught: retain two equivalent server routes and emit duplicate ciphertext for one
    // recipient instead of selecting one deterministic route.
    @Test
    fun equivalentDuplicateRoutesMaterializeOneLexicographicallySelectedEnvelope() {
        EventStore.append(sender.context, localEvent(EVENT_ID).copy(targetTopic = ""))
        assertTrue(sender.peers.pin(recipient.installId, recipient.identity))
        http.routes = listOf(route("TEST-ONLY-route-z", recipient), route("TEST-ONLY-route-a", recipient))

        val outbox = sender.outbox(senderApi)
        assertEquals(1, outbox.materializePending())
        assertEquals(listOf("TEST-ONLY-route-a"), outbox.recordsFor(EVENT_ID).map { it.outerContext.routeId })
    }

    // Mutation caught: choose an arbitrary server identity when route records for a recipient
    // conflict, turning route metadata into a trust root.
    @Test
    fun conflictingDuplicateRoutesFailClosedWithoutAnyEnqueue() {
        val substituted = device("TEST-ONLY-conflicting-route")
        EventStore.append(sender.context, localEvent(EVENT_ID).copy(targetTopic = ""))
        assertTrue(sender.peers.pin(recipient.installId, recipient.identity))
        http.routes = listOf(route(ROUTE_ID, recipient), route(ROUTE_ID_B, substituted).copy(recipientInstallId = recipient.installId))

        val outbox = sender.outbox(senderApi)
        assertEquals(0, outbox.materializePending())
        assertFalse(outbox.flush())
        assertTrue(outbox.recordsFor(EVENT_ID).isEmpty())
        assertTrue(http.acceptedEnvelopes.isEmpty())
    }

    // Mutation caught: delete accepted evidence before it is possible to recover a crash after
    // source sync, forcing a later flush to recreate or resend recipient ciphertext.
    @Test
    fun crashAfterSourceSyncedBeforeCleanupCompactsAcceptedRecordsWithoutResending() {
        val other = device("TEST-ONLY-finalize-b")
        EventStore.append(sender.context, localEvent(EVENT_ID).copy(targetTopic = ""))
        assertTrue(sender.peers.pin(recipient.installId, recipient.identity))
        assertTrue(sender.peers.pin(other.installId, other.identity))
        http.routes = listOf(route(ROUTE_ID, recipient), route(ROUTE_ID_B, other))
        val crash = object : RelayOutboxFaults {
            override fun afterSourceSyncedBeforeCleanup(sourceEventId: String) { throw IOException("TEST-ONLY") }
        }

        assertFalse(sender.outbox(senderApi, crash).flush())
        assertEquals(2, http.acceptedEnvelopes.size)
        assertEquals("synced", EventStore.load(sender.context).single { it.eventId == EVENT_ID }.syncState)

        val reconstructed = sender.outbox(senderApi)
        assertTrue(reconstructed.flush())
        assertEquals(2, http.acceptedEnvelopes.size)
        assertTrue(reconstructed.recordsFor(EVENT_ID).isEmpty())
    }

    // Mutation caught: strand all accepted records if the process dies after the final recipient
    // acceptance was persisted but before source sync, then enqueue them again on reconstruction.
    @Test
    fun crashAfterFinalAcceptanceBeforeSourceSyncFinalizesWithoutResending() {
        val other = device("TEST-ONLY-before-sync-b")
        EventStore.append(sender.context, localEvent(EVENT_ID).copy(targetTopic = ""))
        assertTrue(sender.peers.pin(recipient.installId, recipient.identity))
        assertTrue(sender.peers.pin(other.installId, other.identity))
        http.routes = listOf(route(ROUTE_ID, recipient), route(ROUTE_ID_B, other))
        val crash = object : RelayOutboxFaults {
            override fun beforeSourceSynced(sourceEventId: String) { throw IOException("TEST-ONLY") }
            override fun afterSourceSyncedBeforeCleanup(sourceEventId: String) = Unit
        }

        assertFalse(sender.outbox(senderApi, crash).flush())
        assertEquals(2, http.acceptedEnvelopes.size)
        assertEquals("pending", EventStore.load(sender.context).single { it.eventId == EVENT_ID }.syncState)

        val reconstructed = sender.outbox(senderApi)
        assertTrue(reconstructed.flush())
        assertEquals(2, http.acceptedEnvelopes.size)
        assertEquals("synced", EventStore.load(sender.context).single { it.eventId == EVENT_ID }.syncState)
        assertTrue(reconstructed.recordsFor(EVENT_ID).isEmpty())
    }

    // Mutation caught: use decrypted actor/target topics without binding them to authenticated outer
    // install IDs, allowing a valid peer signature to relay a payload for another actor or target.
    @Test
    fun inboxRejectsActorOrTargetThatDoesNotBindToTheAuthenticatedOuterContext() {
        val actorMismatch = inboundEnvelope(
            messageId = "TEST-ONLY-actor-mismatch",
            payload = inboundPayload(EVENT_ID).put("actorTopic", "TEST-ONLY-someone-else")
        )
        val targetMismatch = inboundEnvelope(
            messageId = "TEST-ONLY-target-mismatch",
            payload = inboundPayload(EVENT_ID_B).put("targetTopic", "TEST-ONLY-someone-else")
        )
        http.inboxEnvelopes = listOf(actorMismatch, targetMismatch)

        assertTrue(recipient.inbox(recipientApi).reconcile())

        assertFalse(EventStore.contains(recipient.context, EVENT_ID))
        assertFalse(EventStore.contains(recipient.context, EVENT_ID_B))
        assertEquals(setOf("rejected"), http.terminalAcks.map { it.outcome }.toSet())
    }

    // Mutation caught: append/apply the same accepted delivery twice instead of recognizing its
    // durable event/receipt state during at-least-once replay.
    @Test
    fun duplicateDeliveryHasExactlyOnceEffectiveDomainStateAndReceivesDuplicateAck() {
        val envelope = inboundEnvelope("TEST-ONLY-duplicate", inboundPayload(EVENT_ID))
